"""Tests for manual-edge scenarios in the rational-world test schema.

These tests verify the schema setup for two cases where lineage cannot
be determined automatically from SQL and must be connected via manual edges:

1. **External Python process** (extends deep chain):
   staging.input_proceso_python  ~~manual~~>  staging.output_proceso_python
   An external Python script reads from the input table and writes enriched
   data to the output table.  No SQL relates them.

2. **Script view with commented CREATE TABLE** (extends Chain A):
   staging.script_crear_resumen  ~~manual~~>  analytics.resumen_creado
   The view contains `-- create or replace table ...` and was executed
   manually to populate the target table.  The SQL in the view traces
   back to analytics.customer_summary (tested in test_parse_script_view.py),
   but the link from the view to the table is manual.
"""

import pytest

from lineage_tracker.models import LineageEdge, ColumnMapping


class TestExternalPythonProcess:
    """Verify schema compatibility for the manual edge between
    input_proceso_python and output_proceso_python."""

    def test_input_table_exists_in_schemas(self, schemas):
        assert "staging.input_proceso_python" in schemas

    def test_output_table_exists_in_schemas(self, schemas):
        assert "staging.output_proceso_python" in schemas

    def test_input_has_no_view_sql(self, view_sql):
        """Input is a table, not a view — no SQL to parse."""
        assert "staging.input_proceso_python" not in view_sql

    def test_output_has_no_view_sql(self, view_sql):
        """Output is a table, not a view — no SQL to parse."""
        assert "staging.output_proceso_python" not in view_sql

    def test_shared_columns_user_id_and_segment(self, schemas):
        """Both tables share user_id and segment — the Python process
        carries these through."""
        input_cols = set(schemas["staging.input_proceso_python"])
        output_cols = set(schemas["staging.output_proceso_python"])
        shared = input_cols & output_cols
        assert "user_id" in shared
        assert "segment" in shared

    def test_output_has_derived_columns(self, schemas):
        """The Python process adds score and recommendation."""
        output_cols = set(schemas["staging.output_proceso_python"])
        assert "score" in output_cols
        assert "recommendation" in output_cols

    def test_manual_edge_can_be_constructed(self, schemas):
        """Verify a manual edge with column mappings can be built."""
        edge = LineageEdge(
            id="manual_staging.input_proceso_python__staging.output_proceso_python",
            source_node="staging.input_proceso_python",
            target_node="staging.output_proceso_python",
            edge_type="manual",
            description="External Python process: reads input, computes score/recommendation",
            column_mappings=[
                ColumnMapping(
                    source_columns=["user_id"],
                    target_column="user_id",
                    transformation="direct",
                ),
                ColumnMapping(
                    source_columns=["segment"],
                    target_column="segment",
                    transformation="direct",
                ),
                ColumnMapping(
                    source_columns=["pages_visited", "total_time_spent"],
                    target_column="score",
                    transformation="external",
                    description="Computed by Python ML model from pages_visited and total_time_spent",
                ),
                ColumnMapping(
                    source_columns=["segment", "pages_visited"],
                    target_column="recommendation",
                    transformation="external",
                    description="Generated by Python rules engine based on segment and pages_visited",
                ),
            ],
        )
        assert edge.edge_type == "manual"
        assert len(edge.column_mappings) == 4
        target_cols = {m.target_column for m in edge.column_mappings}
        assert target_cols == set(schemas["staging.output_proceso_python"])


class TestScriptCrearResumenManualEdge:
    """Verify schema compatibility for the manual edge between
    script_crear_resumen (view) and resumen_creado (table)."""

    def test_view_exists_in_schemas(self, schemas):
        assert "staging.script_crear_resumen" in schemas

    def test_table_exists_in_schemas(self, schemas):
        assert "analytics.resumen_creado" in schemas

    def test_view_has_sql(self, view_sql):
        """The view IS a parseable SQL definition."""
        assert "staging.script_crear_resumen" in view_sql

    def test_table_has_no_view_sql(self, view_sql):
        """The target table has no view SQL — it was created manually."""
        assert "analytics.resumen_creado" not in view_sql

    def test_view_sql_starts_with_comment(self, view_sql):
        """The view SQL starts with a -- create or replace table comment."""
        sql = view_sql["staging.script_crear_resumen"]
        first_line = sql.strip().split("\n")[0]
        assert first_line.startswith("-- create or replace table")
        assert "resumen_creado" in first_line

    def test_schemas_match(self, schemas):
        """View and table have identical columns — the table was created
        from the view's output."""
        view_schema = schemas["staging.script_crear_resumen"]
        table_schema = schemas["analytics.resumen_creado"]
        assert view_schema == table_schema

    def test_manual_edge_can_be_constructed(self, schemas):
        """Verify a manual edge with column mappings can be built."""
        edge = LineageEdge(
            id="manual_staging.script_crear_resumen__analytics.resumen_creado",
            source_node="staging.script_crear_resumen",
            target_node="analytics.resumen_creado",
            edge_type="manual",
            description="View was executed manually to create table resumen_creado",
            column_mappings=[
                ColumnMapping(
                    source_columns=[col],
                    target_column=col,
                    transformation="direct",
                )
                for col in schemas["analytics.resumen_creado"]
            ],
        )
        assert edge.edge_type == "manual"
        assert len(edge.column_mappings) == len(schemas["analytics.resumen_creado"])
